// =============================================================================
// LORE — Profile View (Manager, per-Employee)
// The Manager's per-Employee intelligence surface. This view is not navigated
// to directly — it is launched from the Dashboard team list when the Manager
// clicks on an Employee's card.
//
// What the Manager sees here:
//   - Employee's rank and total XP
//   - Mastery by skill area (played/correct breakdown, shown as a progress bar)
//   - Learning velocity (recent sessions vs. earlier sessions compared)
//   - Plain-language summary generated by AI from the training signal
//   - Session count and calibration status
//
// What the Employee never sees:
//   - patternSignals (cognitive pattern observations, Manager-facing only)
//   - The plain-language summary (they would find it unsettling)
//   - Raw XP numbers are visible to the Employee themselves in the nav bar;
//     the Manager sees the same numbers with more context around them.
//
// This view is reached via app.js routing: app.js handles ?employee=UID in the
// URL and calls initProfile(orgId, employeeId) if the current user is a Manager.
//
// Import paths: views/ files import engine files using ../engine/[file].js.
// =============================================================================

import { getRankForXP, RANKS } from '../engine/state.js';

// ---------------------------------------------------------------------------
// Entry point — called by app.js when a Manager navigates to an Employee.
// employeeId: the Firestore UID of the Employee being viewed.
// ---------------------------------------------------------------------------
export async function initProfile(orgId, employeeId) {
    console.log('LORE profile.js: initProfile — orgId:', orgId, 'employeeId:', employeeId);
    const container = document.getElementById('profile-content');
    if (!container) return;

    renderLoading(container, 'Loading profile…');

    const data = await _loadEmployeeData(orgId, employeeId);

    if (!data) {
        container.innerHTML = `
            <div class="empty-state">
                <h3>Profile not found</h3>
                <p class="mt-2">We couldn't load this team member's profile. They may not have signed in yet.</p>
                <button class="btn btn-secondary mt-6" id="back-to-dash">Back to dashboard</button>
            </div>
        `;
        document.getElementById('back-to-dash')?.addEventListener('click', () => {
            window.history.back();
        });
        return;
    }

    renderProfile(container, data, orgId);
}

// ---------------------------------------------------------------------------
// Load all Employee data from Firestore — profile, stats, and recipe library.
// Returns a combined data object or null on failure.
// ---------------------------------------------------------------------------
async function _loadEmployeeData(orgId, employeeId) {
    const { db } = await import('../engine/../firebase.js');
    const {
        doc,
        getDoc,
        collection,
        getDocs
    } = await import('https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js');

    try {
        // Main user document — xp, streak, domainMastery, sessionsTotal
        const userSnap = await getDoc(
            doc(db, 'organisations', orgId, 'users', employeeId)
        );
        if (!userSnap.exists()) return null;
        const user = userSnap.data();

        // Recipe library — recipes the Employee has unlocked and saved
        const librarySnap = await getDocs(
            collection(db, 'organisations', orgId, 'users', employeeId, 'recipeLibrary')
        );
        const library = librarySnap.docs.map(d => d.data());

        return {
            uid:          employeeId,
            xp:           user.xp            ?? 0,
            streak:       user.streak         ?? 0,
            sessionsTotal: user.sessionsTotal ?? 0,
            isCalibrated: (user.sessionsTotal ?? 0) >= 20,
            domainMastery: user.domainMastery ?? {},
            displayName:  user.displayName    ?? null,
            roleTitle:    user.roleTitle      ?? null,
            seniority:    user.seniority      ?? null,
            createdAt:    user.createdAt      ?? null,
            lastTrainedAt: user.lastTrainedAt ?? null,
            library,
        };
    } catch (err) {
        console.warn('LORE Profile: Could not load employee data.', err);
        return null;
    }
}

// ---------------------------------------------------------------------------
// Render the full profile view.
// ---------------------------------------------------------------------------
function renderProfile(container, data, orgId) {
    const rank       = getRankForXP(data.xp);
    const name       = data.displayName ?? 'This team member';
    const masteryDomains = Object.keys(data.domainMastery);

    container.innerHTML = `
        <div>
            <!-- Back button -->
            <button class="btn btn-secondary mb-6" id="back-btn" style="font-size: var(--text-sm);">
                ← Back to dashboard
            </button>

            <!-- Header -->
            <div class="flex-between mb-6">
                <div>
                    <h1>${name}</h1>
                    <p class="text-secondary text-sm mt-1">${data.roleTitle ?? ''}</p>
                </div>
                <span class="rank-badge" style="font-size: var(--text-sm);">${rank.name}</span>
            </div>

            <!-- Stats row -->
            <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: var(--space-4); margin-bottom: var(--space-6);">
                <div class="card" style="text-align: center;">
                    <p class="label">XP</p>
                    <p style="font-size: var(--text-2xl); font-weight: 600; margin-top: var(--space-1);">${data.xp.toLocaleString()}</p>
                </div>
                <div class="card" style="text-align: center;">
                    <p class="label">Sessions</p>
                    <p style="font-size: var(--text-2xl); font-weight: 600; margin-top: var(--space-1);">${data.sessionsTotal}</p>
                </div>
                <div class="card" style="text-align: center;">
                    <p class="label">Streak</p>
                    <p style="font-size: var(--text-2xl); font-weight: 600; margin-top: var(--space-1);">${data.streak}</p>
                    <p class="text-xs text-secondary">days</p>
                </div>
            </div>

            <!-- Calibration status -->
            ${renderCalibrationStatus(data)}

            <!-- Skill area mastery -->
            ${masteryDomains.length > 0
                ? renderMasterySection(data.domainMastery)
                : renderNoMastery()
            }

            <!-- Recipe library -->
            ${data.library.length > 0
                ? renderLibrarySection(data.library)
                : ''
            }

            <!-- Plain-language summary — Manager only, generated on demand -->
            <div class="card mt-6" id="summary-card">
                <div class="flex-between mb-4">
                    <h3>Summary</h3>
                    <button class="btn btn-secondary" id="generate-summary" style="font-size: var(--text-sm);">
                        Generate
                    </button>
                </div>
                <p class="text-secondary text-sm" id="summary-text">
                    Generate a plain-language summary of ${name}'s training pattern.
                </p>
            </div>
        </div>
    `;

    document.getElementById('back-btn')?.addEventListener('click', () => {
        // Navigate back to the dashboard — the Manager came from there
        window.history.back();
    });

    _attachSummaryHandler(data, name, orgId);
}

// ---------------------------------------------------------------------------
// Calibration status card.
// Provisional until 20 sessions are complete — mirrors the chess rating model.
// ---------------------------------------------------------------------------
function renderCalibrationStatus(data) {
    if (data.sessionsTotal === 0) {
        return `
            <div class="card mb-6" style="border-left: 3px solid var(--amber-text);">
                <p style="font-weight: 500; color: var(--amber-text);">Calibration pending</p>
                <p class="text-secondary text-sm mt-2">This team member hasn't started training yet. Their baseline will be established after their first session.</p>
            </div>
        `;
    }

    if (!data.isCalibrated) {
        const remaining = 20 - data.sessionsTotal;
        return `
            <div class="card mb-6" style="border-left: 3px solid var(--amber-text);">
                <p style="font-weight: 500; color: var(--amber-text);">Baseline forming</p>
                <p class="text-secondary text-sm mt-2">${remaining} more session${remaining !== 1 ? 's' : ''} until their baseline is confirmed. Numbers up to now are directional.</p>
            </div>
        `;
    }

    return `
        <div class="card mb-6" style="border-left: 3px solid var(--sage);">
            <p style="font-weight: 500; color: var(--sage);">Baseline confirmed</p>
            <p class="text-secondary text-sm mt-2">20 sessions completed. Performance data is reliable enough to track progress meaningfully.</p>
        </div>
    `;
}

// ---------------------------------------------------------------------------
// Skill area mastery breakdown.
// Shows accuracy per domain with a visual bar.
// Bar colour: sage if >= 70% accuracy (strong), amber if 40–70%, ember if < 40%.
// ---------------------------------------------------------------------------
function renderMasterySection(domainMastery) {
    const domains = Object.entries(domainMastery).sort((a, b) => {
        // Sort by number of sessions — most active areas first
        return (b[1].played ?? 0) - (a[1].played ?? 0);
    });

    return `
        <div class="card mb-6">
            <h3 style="margin-bottom: var(--space-4);">Skill area mastery</h3>
            ${domains.map(([domain, stats]) => {
                const played   = stats.played   ?? 0;
                const correct  = stats.correct  ?? 0;
                const accuracy = played > 0 ? Math.round((correct / played) * 100) : 0;
                const barColour = accuracy >= 70
                    ? 'var(--sage)'
                    : accuracy >= 40
                    ? '#D4943A'
                    : 'var(--ember)';
                const label = accuracy >= 70
                    ? 'Strong'
                    : accuracy >= 40
                    ? 'Developing'
                    : 'Building';

                return `
                    <div style="margin-bottom: var(--space-5);">
                        <div class="flex-between mb-2">
                            <p style="font-size: var(--text-sm); font-weight: 500;">${domain}</p>
                            <p class="text-xs text-secondary">${accuracy}% · ${played} session${played !== 1 ? 's' : ''} · ${label}</p>
                        </div>
                        <div class="xp-bar-track">
                            <div class="xp-bar-fill" style="width: ${accuracy}%; background: ${barColour};"></div>
                        </div>
                    </div>
                `;
            }).join('')}
        </div>
    `;
}

function renderNoMastery() {
    return `
        <div class="card mb-6">
            <h3 style="margin-bottom: var(--space-2);">Skill area mastery</h3>
            <p class="text-secondary text-sm">No training sessions completed yet. Mastery data appears here once they start.</p>
        </div>
    `;
}

// ---------------------------------------------------------------------------
// Recipe library — recipes the Employee has saved after unlocking them.
// Shows the Manager which expert patterns have made an impression.
// ---------------------------------------------------------------------------
function renderLibrarySection(library) {
    return `
        <div class="card mb-6">
            <h3 style="margin-bottom: var(--space-4);">Saved recipes</h3>
            <p class="text-secondary text-sm mb-4">Recipes this team member saved to their library after unlocking them — a signal of what resonated.</p>
            ${library.map(item => `
                <div style="padding: var(--space-3) 0; border-bottom: 1px solid rgba(44,36,22,0.06);">
                    <p style="font-size: var(--text-sm); font-weight: 500;">${item.skillName ?? 'Unnamed skill'}</p>
                    <p class="text-xs text-secondary mt-1">${item.domain ?? ''}</p>
                </div>
            `).join('')}
        </div>
    `;
}

// ---------------------------------------------------------------------------
// Plain-language summary — generated on demand by AI.
// The Manager clicks Generate; AI reads the training pattern and writes a
// short, human narrative: what this Employee is strong at, what is still
// forming, where to focus their development.
//
// This never surfaces to the Employee. It is a Manager intelligence tool.
// ---------------------------------------------------------------------------
function _attachSummaryHandler(data, name, orgId) {
    document.getElementById('generate-summary')?.addEventListener('click', async () => {
        const btn    = document.getElementById('generate-summary');
        const textEl = document.getElementById('summary-text');
        btn.disabled    = true;
        btn.textContent = 'Generating…';
        if (textEl) textEl.textContent = '';

        const { generate } = await import('../engine/ai.js');

        const masteryText = Object.entries(data.domainMastery).map(([domain, stats]) => {
            const acc = stats.played > 0
                ? Math.round((stats.correct / stats.played) * 100)
                : 0;
            return `${domain}: ${acc}% accuracy across ${stats.played} sessions`;
        }).join('; ');

        const systemPrompt = `You are writing a brief plain-language summary for a manager about one of their team members' training performance.
Tone: like a trusted colleague sharing an observation. Warm but precise. Not clinical, not generic.
Length: 2 to 4 sentences.
Avoid: scores, percentages, the word "pattern", the phrase "your data shows", any technical system language.
Describe: what they seem to understand well, where the instinct is still forming, and one specific, grounded observation the manager could act on.
Do not mention LORE, training, or the platform — write as if you watched them work.`;

        const prompt = `Team member: ${name}
Role: ${data.roleTitle ?? 'Not specified'}
Experience level: ${data.seniority ?? 'Not specified'}
Sessions completed: ${data.sessionsTotal}
Skill area performance: ${masteryText || 'No sessions yet'}

Write the summary.`;

        console.log('LORE profile.js: Generating AI summary for employee:', data.uid);
        const result = await generate(prompt, systemPrompt);

        btn.disabled    = false;
        btn.textContent = 'Regenerate';

        if (!result.ok) {
            console.warn('LORE profile.js: Summary generation failed.');
            if (textEl) textEl.textContent = 'Could not generate summary right now. Try again shortly.';
            return;
        }
        console.log('LORE profile.js: Summary generated successfully.');

        if (textEl) {
            textEl.textContent = result.text;
            textEl.style.color = 'var(--ink)';
            textEl.style.lineHeight = '1.8';
        }
    });
}

// ---------------------------------------------------------------------------
// Loading state.
// ---------------------------------------------------------------------------
function renderLoading(container, message) {
    container.innerHTML = `
        <div class="empty-state">
            <div class="spinner"></div>
            <p class="text-secondary mt-4">${message}</p>
        </div>
    `;
}